language: php
dist: trusty
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files
matrix:
  include:
    - php: 5.6
    - php: 7.3
  allow_failures:
    - php: 7.3
  fast_finish: true
before_script:
  - composer install
script:
  - PATH=$HOME/.composer/vendor/bin:$PATH ./build.sh
